name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-build.[0-9]+'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Install tanzu cli
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        echo "deb https://storage.googleapis.com/tanzu-cli-os-packages/apt tanzu-cli-jessie main" | sudo tee /etc/apt/sources.list.d/tanzu.list
        sudo apt update --allow-insecure-repositories
        sudo apt-get install tanzu-cli
        tanzu ceip-participation set false
        tanzu version
        tanzu config get
        tanzu plugin search

