name: CI

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'

env:
  GOPRIVATE: github.com/pivotal,github.com/vmware-tanzu-private/*,github.com/vmware-tanzu/tanzu-framework
  TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.x
    - name: Setup
      run: |
        git config --global url."https://app-accelerator-build:${TOKEN}@github.com".insteadOf "https://github.com"
        kind create cluster
    - name: Install tanzu cli
      run: |
        curl -o tanzu https://storage.googleapis.com/tanzu-cli/artifacts/core/latest/tanzu-core-linux_amd64 && \
          sudo mv tanzu /usr/local/bin/tanzu && \
          chmod +x /usr/local/bin/tanzu
        env
        tanzu init
        tanzu plugin repo add -b tanzu-cli-admin-plugins -n admin -p artifacts-admin
        tanzu plugin install builder
        tanzu plugin install test
        tanzu plugin list
    - name: Test
      run: make test
    - name: Create Artifact
      run: make create-artifact
    - uses: actions/upload-artifact@v2
      with:
        name: tanzu-accelerator-plugin.tar.gz
        path: tanzu-accelerator-plugin.tar.gz
        retention-days: 1
  release:
    needs:
    - unit
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Draft release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: true
    - name: Download staged CLI binaries
      uses: actions/download-artifact@v2.0.10
      with:
        name: tanzu-accelerator-plugin.tar.gz
    - name: Upload CLI release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: tanzu-accelerator-plugin.tar.gz
        asset_name: tanzu-accelerator-plugin-${{ steps.get_version.outputs.VERSION }}.tar.gz
        asset_content_type: application/gzip
