name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-build.[0-9]+'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - name: Install tanzu cli
      run: |
        curl -I https://projects.registry.vmware.com
        curl -L -o tanzu-cli-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-cli/releases/download/v0.90.0-alpha.1/tanzu-cli-linux-amd64.tar.gz && \
          mkdir -p tanzu && \
          tar xvzf tanzu-cli-linux-amd64.tar.gz -C tanzu
        sudo install tanzu/v0.90.0-alpha.1/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
        tanzu ceip-participation set false
        tanzu version
        tanzu plugin search
        tanzu plugin install builder --version v0.90.0-alpha.1 --target global

