name: CI

on:
  push:
    branches:
    - '**'
    tags:
    - '**'

env:
  GOPRIVATE: github.com/pivotal,github.com/vmware-tanzu/*
  TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.x
    - name: Setup
      run: |
        git config --global url."https://app-accelerator-build:${TOKEN}@github.com".insteadOf "https://github.com"
        kind create cluster
    - name: Install tanzu cli
      run: |
        curl -L -o tanzu-cli-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-framework/releases/download/v0.17.0/tanzu-cli-linux-amd64.tar.gz && \
          mkdir -p tanzu && \
          tar xvzf tanzu-cli-linux-amd64.tar.gz -C tanzu
        sudo install tanzu/v0.17.0/tanzu-core-linux_amd64 /usr/local/bin/tanzu
        curl -L -o tanzu-framework-plugins-admin-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-framework/releases/download/v0.17.0/tanzu-framework-plugins-admin-linux-amd64.tar.gz && \
          tar xvzf tanzu-framework-plugins-admin-linux-amd64.tar.gz
        tanzu plugin install builder -l admin-plugins
        tanzu plugin install test -l admin-plugins
    - name: Test
      run: make test
    - name: Create Artifact
      run: make create-artifact
    - name: Install
      run: tanzu plugin install accelerator --local standalone/linux-amd64 --version $(cat BUILD_VERSION)
    - name: Verify docs
      run: |
        rm -rf docs
        tanzu accelerator docs --directory docs
        git diff --exit-code docs
    - uses: actions/upload-artifact@v2
      with:
        name: tanzu-accelerator-plugin.tar.gz
        path: tanzu-accelerator-plugin.tar.gz
        retention-days: 1

  e2e:    
    needs: unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
        - 1.21.1
    env:
      ACC_SERVER_URL: http://localhost:8877
      TANZUNET_ROBOT: ${{ secrets.TANZUNET_ROBOT }}
      TANZUNET_PASS: ${{ secrets.TANZUNET_PASS }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: vmware-tanzu/carvel-setup-action@v1
    - name: Download plugin bundle
      uses: actions/download-artifact@v2
      with:
        name: tanzu-accelerator-plugin.tar.gz
    - name: Install tanzu cli
      run: |
        curl -L -o tanzu-cli-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-framework/releases/download/v0.17.0/tanzu-cli-linux-amd64.tar.gz && \
          mkdir -p tanzu && \
          tar xvzf tanzu-cli-linux-amd64.tar.gz -C tanzu
        sudo install tanzu/v0.17.0/tanzu-core-linux_amd64 /usr/local/bin/tanzu
    - name: Build Version
      run: echo "BUILD_VERSION=$(cat BUILD_VERSION)" >> $GITHUB_ENV          
    - name: Install CLI
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        tar -xvf tanzu-accelerator-plugin.tar.gz
        tanzu plugin install accelerator --local standalone/linux-amd64 --version ${{env.BUILD_VERSION}}
    - name: Create Context
      run: |
        make create-context
    - name: Test CLI commands
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        echo "##[group]List Accelerators"
          tanzu accelerator list
        echo "##[endgroup]"
        echo "##[group]Create Accelerator"
          tanzu accelerator create test-accelerator --git-repository http://www.test.com
        echo "##[endgroup]"
        echo "##[group]Get Acceletor"
          tanzu accelerator get spring-petclinic
        echo "##[endgroup]"
        echo "##[group]Update Accelerator"
          tanzu accelerator update spring-petclinic --description "Lorem Ipsum"
        echo "##[endgroup]"
        echo "##[group]Generate Accelerator"
          tanzu accelerator generate spring-petclinic
        echo "##[endgroup]"
        echo "##[group]Delete Accelerator"
          tanzu accelerator delete test-accelerator
        echo "##[endgroup]"
      if: always()
      continue-on-error: true
    - name: Cleanup
      run: | 
        rm spring-petclinic.zip
        kind delete cluster
      if: always()
    
  release:
    needs:
    - unit
    - e2e
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Draft release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: true
    - name: Download staged CLI binaries
      uses: actions/download-artifact@v2.0.10
      with:
        name: tanzu-accelerator-plugin.tar.gz
    - name: Upload CLI release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: tanzu-accelerator-plugin.tar.gz
        asset_name: tanzu-accelerator-plugin-${{ steps.get_version.outputs.VERSION }}.tar.gz
        asset_content_type: application/gzip
